---
title: "introduction"
output: 
  html_document:
    keep_md: true
    self_contained: true
vignette: >
  %\VignetteIndexEntry{introduction}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Install packages
```{r}
devtools::install_github("fpestana-git/clusteringR",force = F)
devtools::install_github("fpestana-git/visualisR",force = F)
```

```{r setup}
library(clusteringR)
library(dplyr)
library(Seurat)
#library(patchwork)
library(visualisR)
library(ggplot2)
library(rliger)
library(ggpubr)
library(viridis)
#library(pkgload)
```

# Load data
```{r}
# Load the PBMC dataset
pbmc <- Read10X(data.dir = "../data/pbmc/")
```

# Clustering
```{r Clustering}
# Run Seurat clustering using log normalization
seuratLOG <- clusteringSeurat(datasetObject = pbmc,datasetName = "test",metadataAvailable = F,mapTypeValue = "umap",normalizationMethod = "LOG")

# Run Seurat clustering using SCT normalization
seuratSCT <- clusteringSeurat(datasetObject = pbmc,datasetName = "test",metadataAvailable = F,mapTypeValue = "umap",normalizationMethod = "SCT")

# Run LIGER clustering using iNMF algorythm
ligerClustering <- clusteringLiger(datasets = list(pbmc = pbmc),referenceDatasetName = "pbmc", useiNMF = T)
```

# Visualize Dim plot
```{r dimPlot}
drawDimPlot(seuratObject = seuratLOG,datasetName = "pbmc")
drawDimPlot(seuratObject = seuratSCT,datasetName = "pbmc")
drawDimPlotLiger(ligerObject = ligerClustering)

```

# Visualize Feature plot
```{r featurePlot}
drawFeaturePlot(seuratObject = seuratLOG,
                featureValues = c("S100A9","NKG7","LDHB","CD79A"),
                nrowValue = 2,
                ncolValue = 2,
                datasetName = "test")
```

# Visualize Heatmap
```{r heatmap}
# Visualize the variable features
drawHeatmapPlot(seuratObject = seuratLOG,featureNames = c("S100A9","NKG7","LDHB","CD79A"),assaytype = "RNA",plotName = "test",groupValue = "seurat_clusters",drawLinesValue = T)
```

# Visualize Dot plot
```{r dotPlot}
drawDotPlot(seuratObject = seuratLOG,plotName = "test",featureValues = c("S100A9","NKG7","LDHB","CD79A"))
```

